import { existsSync, writeFileSync } from 'fs';
import { join } from 'path';

/**
 * Default `.dockerignore` written at a Container agent's build-context root when `buildContextPath`
 * is set and none exists. Keeps secrets and build junk out of the image and out of the CodeBuild
 * upload. Both local `agentcore dev`/`package` and `agentcore deploy` honor this same file, so what
 * is excluded locally is exactly what is excluded on deploy.
 */
export const BUILD_CONTEXT_DOCKERIGNORE_TEMPLATE = `# Generated by agentcore because this agent sets buildContextPath — the whole of this directory is the
# Docker build context, so secrets/junk here would otherwise be baked into the image and uploaded to
# CodeBuild. Both 'agentcore dev'/'package' and 'agentcore deploy' honor this file. Edit freely; to
# intentionally include a file listed here (e.g. a non-secret .env.production), remove its line.
.env
.env.*
.git/
node_modules/
.venv/
__pycache__/
agentcore/
`;

/**
 * Ensure a `.dockerignore` exists at the resolved build-context root. No-op when one already exists
 * (the user's file is never overwritten). Returns the path when it creates one, otherwise null.
 *
 * Called only when `buildContextPath` is set — that is when the context is widened beyond the agent's
 * own `codeLocation` (e.g. to a monorepo root) and a stray root-level `.env`/`.git` would be swept in.
 */
export function ensureBuildContextDockerignore(resolvedBuildContext: string): string | null {
  const dockerignorePath = join(resolvedBuildContext, '.dockerignore');
  if (existsSync(dockerignorePath)) {
    return null;
  }
  writeFileSync(dockerignorePath, BUILD_CONTEXT_DOCKERIGNORE_TEMPLATE);
  return dockerignorePath;
}
