import { existsSync, writeFileSync } from 'fs';
import { join } from 'path';

/**
 * Default `.dockerignore` written at a Container agent's build-context root when `buildContextPath`
 * is set and none exists. Keeps secrets and build junk out of the image and out of the CodeBuild
 * upload. Both local `agentcore dev`/`package` and `agentcore deploy` honor this same file, so what
 * is excluded locally is exactly what is excluded on deploy.
 */
export const BUILD_CONTEXT_DOCKERIGNORE_TEMPLATE = `# Generated by agentcore because this agent sets buildContextPath — the whole of this directory is the
# Docker build context, so secrets/junk here would otherwise be baked into the image and uploaded to
# CodeBuild. Patterns are listed both bare and '**/'-prefixed so nested copies (e.g.
# app/agent-one/node_modules, app/agent-one/.env) are excluded too, not just the top level — Docker
# matches .dockerignore patterns root-relative. Both 'agentcore dev'/'package' and 'agentcore deploy'
# honor this file. Edit freely; to intentionally include a file listed here (e.g. a non-secret
# .env.production), add a '!'-prefixed line for it below.
.env
.env.*
**/.env
**/.env.*
.git
**/.git
.venv
**/.venv
node_modules
**/node_modules
__pycache__
**/__pycache__
.pytest_cache
**/.pytest_cache
.DS_Store
**/.DS_Store
agentcore/
`;

/**
 * Ensure a `.dockerignore` exists at the resolved build-context root. No-op when the directory does
 * not exist or a `.dockerignore` is already present (the user's file is never overwritten). Returns
 * the path when it creates one, otherwise null.
 *
 * Guards the DIRECTORY, not just the file: a missing/typo'd `buildContextPath` would otherwise make
 * `writeFileSync` throw a raw ENOENT — crashing `agentcore dev`, bypassing `PackagingError` in
 * `package`, and masking preflight's friendly "Dockerfile not found". Callers invoke this only AFTER
 * validating that the Dockerfile exists, so on a failing build/deploy no stray `.dockerignore` is
 * left behind.
 *
 * Called only when `buildContextPath` is set — that is when the context is widened beyond the agent's
 * own `codeLocation` (e.g. to a monorepo root) and a stray root-level `.env`/`.git` would be swept in.
 */
export function ensureBuildContextDockerignore(resolvedBuildContext: string): string | null {
  if (!existsSync(resolvedBuildContext)) {
    return null;
  }
  const dockerignorePath = join(resolvedBuildContext, '.dockerignore');
  if (existsSync(dockerignorePath)) {
    return null;
  }
  writeFileSync(dockerignorePath, BUILD_CONTEXT_DOCKERIGNORE_TEMPLATE);
  return dockerignorePath;
}
