# Proxy runtime for the imported Amazon Bedrock Agent "{{agentName}}".
# Generated by `agentcore project create/add runtime --type import`. Requests to
# this runtime are forwarded to the Bedrock Agent, and its reply is streamed
# back — edit or replace this file to take ownership of the behavior.

import os
import uuid

import boto3
from bedrock_agentcore.runtime import BedrockAgentCoreApp

AGENT_ID = os.environ.get("BEDROCK_AGENT_ID", "{{agentId}}")
AGENT_ALIAS_ID = os.environ.get("BEDROCK_AGENT_ALIAS_ID", "{{agentAliasId}}")
AGENT_REGION = os.environ.get("BEDROCK_AGENT_REGION", "{{agentRegion}}")

app = BedrockAgentCoreApp()
client = boto3.client("bedrock-agent-runtime", region_name=AGENT_REGION)


@app.entrypoint
async def invoke(payload, context):
    """Forward the prompt to the Bedrock Agent and stream its completion."""
    prompt = payload.get("prompt", "")
    if not isinstance(prompt, str) or not prompt:
        yield "No query provided; include a 'prompt' field in the payload."
        return

    # Bedrock Agent sessions require ids of 2+ chars; reuse the runtime session
    # so multi-turn conversations keep the agent's own memory of the exchange.
    session_id = context.session_id or payload.get("sessionId") or uuid.uuid4().hex

    response = client.invoke_agent(
        agentId=AGENT_ID,
        agentAliasId=AGENT_ALIAS_ID,
        sessionId=session_id,
        inputText=prompt,
    )
    for event in response["completion"]:
        chunk = event.get("chunk")
        if chunk and "bytes" in chunk:
            yield chunk["bytes"].decode("utf-8")


if __name__ == "__main__":
    app.run()
