import { createHash } from "node:crypto";
import { existsSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { InputValidationError, InvalidEnvironmentError } from "../../errors";
import type { DevEvent, DevRunner, DevServerInput } from "../../handlers/project/dev/types";
import {
  MissingToolError,
  streamProcess,
  toolAvailable,
  type ProcessStreamer,
  type StreamProcessOptions,
} from "../../io";

const CONTAINER_TOOLS = ["docker", "podman", "finch"] as const;
const CLEANUP_TIMEOUT_MS = 2_000;
const DOCKERFILE_NAME = "Dockerfile";
const CONTAINER_RUNTIME_INSTALL_HINT =
  "Install Docker (https://docs.docker.com/get-docker/), Podman (https://podman.io/), " +
  "or Finch (https://runfinch.com/).";

const BUILD_CONTEXT_DOCKERIGNORE = `# Generated by agentcore because buildContextPath widens the Docker build context.
.env
.env.*
**/.env
**/.env.*
.git
**/.git
.venv
**/.venv
node_modules
**/node_modules
__pycache__
**/__pycache__
.pytest_cache
**/.pytest_cache
.DS_Store
**/.DS_Store
agentcore/
`;

type ContainerTool = (typeof CONTAINER_TOOLS)[number];
type ToolAvailable = typeof toolAvailable;

type ContainerDevRunnerConfig = {
  streamProcess?: ProcessStreamer;
  toolAvailable?: ToolAvailable;
};

export class ContainerDevRunner implements DevRunner {
  private readonly streamProcess: ProcessStreamer;
  private readonly toolAvailable: ToolAvailable;

  constructor(config: ContainerDevRunnerConfig = {}) {
    this.streamProcess = config.streamProcess ?? streamProcess;
    this.toolAvailable = config.toolAvailable ?? toolAvailable;
  }

  public async *run(input: DevServerInput): AsyncGenerator<DevEvent, void> {
    input.signal.throwIfAborted();
    const context = join(
      input.projectRoot,
      input.runtime.buildContextPath ?? input.runtime.codeLocation,
    );
    if (!isDirectory(context)) {
      throw new InputValidationError(`container build context directory not found: ${context}`);
    }

    const dockerfile = input.runtime.dockerfile ?? DOCKERFILE_NAME;
    const dockerfilePath = join(context, dockerfile);
    if (!isFile(dockerfilePath)) {
      throw new InputValidationError(`container Dockerfile not found: ${dockerfilePath}`);
    }

    const tool = await this.resolveContainerTool(input.signal);
    input.signal.throwIfAborted();
    if (input.runtime.buildContextPath) {
      const dockerignore = ensureBuildContextDockerignore(context);
      if (dockerignore) {
        yield { type: "status", message: `Created protective ${dockerignore}` };
      }
    }

    const runtimeName = input.runtime.name.toLowerCase();
    const projectId = hashString(resolve(input.projectRoot));
    const imageTag = `agentcore-dev/${sanitizeImageNameComponent(runtimeName)}-${projectId}`;
    const containerName = `agentcore-dev-${runtimeName}-${projectId}`;
    await this.removeContainer(tool, containerName, context);
    input.signal.throwIfAborted();

    const buildArgs = input.runtime.customDockerBuildArgs ?? {};
    const buildArgFlags = Object.entries(buildArgs).flatMap(([key, value]) => [
      "--build-arg",
      `${key}=${value}`,
    ]);
    const redactedBuildArgFlags = Object.keys(buildArgs).flatMap((key) => [
      "--build-arg",
      `${key}=<redacted>`,
    ]);
    const buildCommand = [tool, "build", "-f", dockerfile, "-t", imageTag, ...buildArgFlags, "."];
    const buildOptions: StreamProcessOptions = {
      cwd: context,
      env: process.env,
      redactedCommand: [
        tool,
        "build",
        "-f",
        dockerfile,
        "-t",
        imageTag,
        ...redactedBuildArgFlags,
        ".",
      ],
      signal: input.signal,
    };

    yield { type: "status", message: `Building image with ${tool}` };
    yield* this.streamProcess(buildCommand, buildOptions);

    const containerPort = portForProtocol(input.runtime.protocol);
    const forwardedEnv: Record<string, string> = {
      ...input.env,
      PORT: String(containerPort),
      LOCAL_DEV: "1",
    };
    if (input.runtime.protocol === "MCP") {
      forwardedEnv.FASTMCP_PORT = String(containerPort);
    }
    const envFlags = Object.entries(forwardedEnv).flatMap(([key, value]) => [
      "-e",
      `${key}=${value}`,
    ]);
    const redactedEnvFlags = Object.keys(forwardedEnv).flatMap((key) => [
      "-e",
      `${key}=<redacted>`,
    ]);
    const runCommand = [
      tool,
      "run",
      "--rm",
      "--name",
      containerName,
      "-p",
      `127.0.0.1:${input.port}:${containerPort}`,
      ...envFlags,
      imageTag,
    ];

    yield { type: "status", message: "Starting container" };
    try {
      yield* this.streamProcess(runCommand, {
        cwd: context,
        env: process.env,
        redactedCommand: [
          tool,
          "run",
          "--rm",
          "--name",
          containerName,
          "-p",
          `127.0.0.1:${input.port}:${containerPort}`,
          ...redactedEnvFlags,
          imageTag,
        ],
        signal: input.signal,
      });
    } finally {
      await this.removeContainer(tool, containerName, context);
    }
  }

  private async resolveContainerTool(signal: AbortSignal): Promise<ContainerTool> {
    for (const tool of CONTAINER_TOOLS) {
      const hasVersion = await this.toolAvailable(tool);
      signal.throwIfAborted();
      if (!hasVersion) continue;

      const canBuild = await this.toolAvailable(tool, ["build", "--help"]);
      signal.throwIfAborted();
      if (canBuild) return tool;
      if (tool === "finch") {
        throw new InvalidEnvironmentError(
          "Finch is installed but its VM is not initialized. Run 'finch vm init' and retry.",
        );
      }
    }
    throw new MissingToolError("container runtime", CONTAINER_RUNTIME_INSTALL_HINT);
  }

  private async removeContainer(
    tool: ContainerTool,
    containerName: string,
    cwd: string,
  ): Promise<void> {
    try {
      for await (const _event of this.streamProcess([tool, "rm", "-f", containerName], {
        cwd,
        signal: AbortSignal.timeout(CLEANUP_TIMEOUT_MS),
      })) {
        // Best-effort cleanup intentionally discards command output.
      }
    } catch {
      // A missing container and an unavailable daemon are both safe to ignore here.
    }
  }
}

function portForProtocol(protocol: DevServerInput["runtime"]["protocol"]): number {
  if (protocol === "MCP") return 8000;
  if (protocol === "A2A") return 9000;
  return 8080;
}

function isDirectory(path: string): boolean {
  try {
    return statSync(path).isDirectory();
  } catch {
    return false;
  }
}

function isFile(path: string): boolean {
  try {
    return statSync(path).isFile();
  } catch {
    return false;
  }
}

function ensureBuildContextDockerignore(context: string): string | undefined {
  const dockerignore = join(context, ".dockerignore");
  if (existsSync(dockerignore)) return undefined;
  writeFileSync(dockerignore, BUILD_CONTEXT_DOCKERIGNORE);
  return dockerignore;
}

function hashString(value: string): string {
  return createHash("sha256").update(value).digest("hex").slice(0, 12);
}

function sanitizeImageNameComponent(value: string): string {
  return value.replace(/_{3,}/g, "__");
}
