import { createHash, randomUUID } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { rm, writeFile } from "node:fs/promises";
import { homedir, tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { InputValidationError, InvalidEnvironmentError } from "../../errors";
import type { DevEvent, DevRunner, DevServerInput } from "../../handlers/project/dev/types";
import {
  MissingToolError,
  streamProcess,
  toolAvailable,
  type ProcessStreamer,
  type StreamProcessOptions,
} from "../../io";
import { isDirectory, isFile, resolvePathWithinProject } from "./path";
import { DEV_PORTS } from "./port";

const CONTAINER_TOOLS = ["docker", "podman", "finch"] as const;
const AWS_ENV_KEYS = [
  "AWS_ACCESS_KEY_ID",
  "AWS_SECRET_ACCESS_KEY",
  "AWS_SESSION_TOKEN",
  "AWS_REGION",
  "AWS_DEFAULT_REGION",
  "AWS_PROFILE",
] as const;
const CLEANUP_TIMEOUT_MS = 2_000;
const DOCKERFILE_NAME = "Dockerfile";
const CONTAINER_RUNTIME_INSTALL_HINT =
  "Install Docker (https://docs.docker.com/get-docker/), Podman (https://podman.io/), " +
  "or Finch (https://runfinch.com/).";

const BUILD_CONTEXT_DOCKERIGNORE = `# Generated by agentcore because buildContextPath widens the Docker build context.
.env
.env.*
**/.env
**/.env.*
.git
**/.git
.venv
**/.venv
node_modules
**/node_modules
__pycache__
**/__pycache__
.pytest_cache
**/.pytest_cache
.DS_Store
**/.DS_Store
agentcore/
`;

type ContainerTool = (typeof CONTAINER_TOOLS)[number];
type ToolAvailable = typeof toolAvailable;

type ContainerDevRunnerConfig = {
  streamProcess?: ProcessStreamer;
  toolAvailable?: ToolAvailable;
  awsDirectory?: string;
  processEnv?: NodeJS.ProcessEnv;
};

export class ContainerDevRunner implements DevRunner {
  private readonly streamProcess: ProcessStreamer;
  private readonly toolAvailable: ToolAvailable;
  private readonly awsDirectory: string;
  private readonly processEnv: NodeJS.ProcessEnv;

  constructor(config: ContainerDevRunnerConfig = {}) {
    this.streamProcess = config.streamProcess ?? streamProcess;
    this.toolAvailable = config.toolAvailable ?? toolAvailable;
    this.awsDirectory = config.awsDirectory ?? join(homedir(), ".aws");
    this.processEnv = config.processEnv ?? process.env;
  }

  public async *run(input: DevServerInput): AsyncGenerator<DevEvent, void> {
    input.signal.throwIfAborted();
    const context = join(
      input.projectRoot,
      input.runtime.buildContextPath ?? input.runtime.codeLocation,
    );
    if (!isDirectory(context)) {
      throw new InputValidationError(`container build context directory not found: ${context}`);
    }

    resolvePathWithinProject(input.projectRoot, context, "container build context");

    const dockerfile = input.runtime.dockerfile ?? DOCKERFILE_NAME;
    const dockerfilePath = join(context, dockerfile);
    if (!isFile(dockerfilePath)) {
      throw new InputValidationError(`container Dockerfile not found: ${dockerfilePath}`);
    }

    const hasAwsCredentials = Boolean(
      (input.env?.AWS_ACCESS_KEY_ID ?? this.processEnv.AWS_ACCESS_KEY_ID) &&
      (input.env?.AWS_SECRET_ACCESS_KEY ?? this.processEnv.AWS_SECRET_ACCESS_KEY),
    );
    const hasAwsConfig = existsSync(this.awsDirectory);
    if (!hasAwsCredentials && !hasAwsConfig) {
      throw new InvalidEnvironmentError(
        "Unable to resolve AWS credentials for the container. Configure AWS credentials " +
          "or set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, then retry.",
      );
    }

    const tool = await this.resolveContainerTool(input.signal);
    input.signal.throwIfAborted();
    if (input.runtime.buildContextPath) {
      const dockerignore = ensureBuildContextDockerignore(context);
      if (dockerignore) {
        yield { type: "status", message: `Created protective ${dockerignore}` };
      }
    }

    const runtimeName = input.runtime.name.toLowerCase();
    const projectId = hashString(resolve(input.projectRoot));
    const imageTag = `agentcore-dev/${sanitizeImageNameComponent(runtimeName)}-${projectId}`;
    const containerName = `agentcore-dev-${runtimeName}-${projectId}`;
    await this.removeContainer(tool, containerName, context);
    input.signal.throwIfAborted();

    const buildArgs = input.runtime.customDockerBuildArgs ?? {};
    const buildArgFlags = Object.entries(buildArgs).flatMap(([key, value]) => [
      "--build-arg",
      `${key}=${value}`,
    ]);
    const redactedBuildArgFlags = Object.keys(buildArgs).flatMap((key) => [
      "--build-arg",
      `${key}=<redacted>`,
    ]);
    const buildCommand = [tool, "build", "-f", dockerfile, "-t", imageTag, ...buildArgFlags, "."];
    const buildOptions: StreamProcessOptions = {
      cwd: context,
      env: this.processEnv,
      redactedCommand: [
        tool,
        "build",
        "-f",
        dockerfile,
        "-t",
        imageTag,
        ...redactedBuildArgFlags,
        ".",
      ],
      signal: input.signal,
    };

    yield { type: "status", message: `Building image with ${tool}` };
    yield* this.streamProcess(buildCommand, buildOptions);

    const containerPort = DEV_PORTS[input.runtime.protocol ?? "HTTP"];
    const forwardedEnv: Record<string, string> = {};
    for (const key of AWS_ENV_KEYS) {
      if (this.processEnv[key]) forwardedEnv[key] = this.processEnv[key];
    }
    Object.assign(forwardedEnv, input.env, {
      PORT: String(containerPort),
      LOCAL_DEV: "1",
    });
    if (input.runtime.protocol === "MCP") {
      forwardedEnv.FASTMCP_PORT = String(containerPort);
    }
    const awsMount = hasAwsConfig ? ["-v", `${this.awsDirectory}:/aws-config:ro`] : [];
    if (awsMount.length) {
      forwardedEnv.AWS_CONFIG_FILE = "/aws-config/config";
      forwardedEnv.AWS_SHARED_CREDENTIALS_FILE = "/aws-config/credentials";
    }
    const envFile = join(tmpdir(), `agentcore-dev-${randomUUID()}.env`);
    try {
      await writeFile(envFile, serializeEnvironment(forwardedEnv), {
        flag: "wx",
        mode: 0o600,
      });
    } catch (error) {
      await rm(envFile, { force: true });
      throw error;
    }
    const runCommand = [
      tool,
      "run",
      "--rm",
      "--name",
      containerName,
      "-p",
      `127.0.0.1:${input.port}:${containerPort}`,
      ...awsMount,
      "--env-file",
      envFile,
      imageTag,
    ];

    yield { type: "status", message: "Starting container" };
    try {
      yield* this.streamProcess(runCommand, {
        cwd: context,
        env: this.processEnv,
        signal: input.signal,
      });
    } finally {
      try {
        await this.removeContainer(tool, containerName, context);
      } finally {
        await rm(envFile, { force: true });
      }
    }
  }

  private async resolveContainerTool(signal: AbortSignal): Promise<ContainerTool> {
    for (const tool of CONTAINER_TOOLS) {
      const hasVersion = await this.toolAvailable(tool);
      signal.throwIfAborted();
      if (!hasVersion) continue;

      const canBuild = await this.toolAvailable(tool, ["build", "--help"]);
      signal.throwIfAborted();
      if (canBuild) return tool;
      if (tool === "finch") {
        throw new InvalidEnvironmentError(
          "Finch is installed but its VM is not initialized. Run 'finch vm init' and retry.",
        );
      }
    }
    throw new MissingToolError("container runtime", CONTAINER_RUNTIME_INSTALL_HINT);
  }

  private async removeContainer(
    tool: ContainerTool,
    containerName: string,
    cwd: string,
  ): Promise<void> {
    try {
      for await (const _event of this.streamProcess([tool, "rm", "-f", containerName], {
        cwd,
        env: this.processEnv,
        signal: AbortSignal.timeout(CLEANUP_TIMEOUT_MS),
      })) {
        // Best-effort cleanup intentionally discards command output.
      }
    } catch {
      // A missing container and an unavailable daemon are both safe to ignore here.
    }
  }
}

function ensureBuildContextDockerignore(context: string): string | undefined {
  const dockerignore = join(context, ".dockerignore");
  if (existsSync(dockerignore)) return undefined;
  writeFileSync(dockerignore, BUILD_CONTEXT_DOCKERIGNORE);
  return dockerignore;
}

function serializeEnvironment(env: Record<string, string>): string {
  return (
    Object.entries(env)
      .map(([key, value]) => {
        if (/[\r\n]/.test(value)) {
          throw new InputValidationError(
            `container environment variable '${key}' cannot contain a newline`,
          );
        }
        return `${key}=${value}`;
      })
      .join("\n") + "\n"
  );
}

function hashString(value: string): string {
  return createHash("sha256").update(value).digest("hex").slice(0, 12);
}

function sanitizeImageNameComponent(value: string): string {
  return value.replace(/_{3,}/g, "__");
}
